### PR TITLE
removes video paragraph type template

### LINKED ISSUE #34: Remove Video Paragraph Type Template - not needed
As far as I can see the video paragraph type template is not needed. On a default install, it does nothing, so if it is being used to any effect, I have a suspicion that it is only being used in custom themes.

If we remove it, then we'll 
- regain the default drupal classes from the paragraph module
- have one less template to maintain
- can remove the template sugggestion from localgov_paragraphs.module (we should probably remove _all_ of those, as paragraphs modules adds them for us anyway in a more conditional manner)

Here's a live coding video of my reasoning - https://www.youtube.com/watch?v=7X8gMJ3oAN0

### PR DESCRIPTION
**Pull request by markconroy**
Closes #34

### CODE REVIEW

**Comment by finnlewis** [comment]
@cjstevens78 @Adnan-cds  - just wanted to check with you both if this would have any impact on Croydon's usage.

**Comment by cjstevens78** [comment]
@finnlewis - as far as i'm aware, we only add youtube videos directly into content via the WYSIWYG media embed and don't have any usage that involves paragraph types but @Adnan-cds can confirm for sure.

**Comment by Adnan-cds** [comment]
We have only **one** [Subsite overview page](https://www.croydon.gov.uk/croydon-needs-foster-carers) in the entire site that uses the localgov_video paragraph type.  This paragraph type may have been contributed by Microserve on behalf of the Bracknell forest council.  So better to check with them as well.  I am copying Gosia @gosia-mlynarczyk

**Review by finnlewis — APPROVED** [review]
Happy to push ahead with this and be clear about the changes in the release notes.

**Comment by finnlewis** [comment]
Oh, sorry, only just saw your messange @Adnan-cds 

@gosia-mlynarczyk will this have any negative impact on you / Bracknell?

**Comment by finnlewis** [comment]
Discussing at Merge Monday's, we'll give it another week before pushing ahead and try to check with Bracknell.

**Comment by markconroy** [comment]
If we do want to keep this file, it might be worth at least editing the markup to be the same as the `localgov_base` markup

```
{%
  set classes = [
    'lgd-video',
    'paragraph',
    'paragraph--type--' ~ paragraph.bundle|clean_class,
    view_mode ? 'paragraph--view-mode--' ~ view_mode|clean_class,
    not paragraph.isPublished() ? 'paragraph--unpublished'
  ]
%}

<div{{ attributes.addClass(classes) }}>
  {{ content }}
</div>
```

At least that way, it renders any field we have in the video paragraph type.

**Pull request merged**
