### PR TITLE
Moved localgov_subsites_paragraphs module to localgov_paragraphs

### PR DESCRIPTION
**Pull request by stephen-cox**
Part of #91

To test this you can do the following:

```sh
composer require localgovdrupal/localgov_paragraphs:"dev-feature/58-move-subsite-paragraphs as 2.1.0"
composer require localgovdrupal/localgov_subsites:"dev-feature/91-move-paragraphs as 2.1.0"
```

### CODE REVIEW

**Comment by stephen-cox** [comment]
Tests are failing until https://github.com/localgovdrupal/localgov_paragraphs/pull/59 is merged and we have a 2.1.0 release of paragraphs

**Review by finnlewis — APPROVED** [review]
Tested this locally and the paragraphs seems to work as expected. 
Thanks @stephen-cox !

**Comment by ekes** [comment]
The update of requirement feels like this should be safe.
I'm still a bit concerned about how it'll play on an existing site.
Have we got a test on an existing site updating, ~~preferably with APCu on~~ (actually there's no classes involved not a problem)?

**Comment by stephen-cox** [comment]
Tested locally with demo content. Just tested this on https://test.localgovdrupal.org/ as well. If there are concerns about this we can ask someone with a live site to test it

**Comment by ekes** [comment]
As it's not got any oo code I think it's fine actually; but can check with others on MM.

**Pull request merged**
