### PR TITLE
Feature/2.x/57 layout paragraphs

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by andybroomfield** [comment]
> 2.0.x Beta / Dev
2.0.x is a complete rewrite of Layout Paragraphs. This branch is experimental, and not for use in production projects. 2.0.x aims to improve the code architecture and offer better APIs for further enhancing the authoring experience.

@finnlewis Can you remind me why we want layout paragraph 2? Is there a missing feature we are needing?

**Comment by finnlewis** [comment]
> @finnlewis Can you remind me why we want layout paragraph 2? Is there a missing feature we are needing?

The motivation is vastly improved user experience. The widget that supports the selection of layouts and paragraphs is confusing in 1.0.0 and 2.x addresses this in a number of ways. 

If the test pass on this, I suggest we start a 3.x branch that we can continue to test against.

I was hoping to be able to test the layout_paragraphs 2.x with the user testing this week, but I'm not sure we'll get it in time.

**Comment by andybroomfield** [comment]
Layout Paragraphs 2 is now stable so we could pick this up now?
Whats involved in the update?

> Versions
2.0.0 Stable
2.0.0 is the most stable, best documented, up-to-date release. Includes automated test coverage for most of the module's functionality.

> 1.0.0 (deprecated)
Upgrading to 2.0.x is recommended. See [Upgrading from 1x to 2x](https://www.drupal.org/docs/contributed-modules/layout-paragraphs/upgrading-from-1x-to-2x) for more information.

Screenshot 2022-08-30 at 10 13 30 am

**Comment by finnlewis** [comment]
Good call @andybroomfield - it would be great to get the better UX in the 2.x branch. I wonder if any of the accessibility concerns that @msayoung have been addressed.

**Comment by finnlewis** [comment]
@msayoung and @stephen-cox thoughts on this? Seems to work really nicely for me now.

**Comment by finnlewis** [comment]
@msayoung could you add a list of critical accessibility issues here? 

We mentioned there are issues to fix on both 1.x and 2.x... but other UX improvements on 2.x ... so we should decide soon. 

My vote is to push ahead with 2.x and fix the issues.

**Comment by msayoung** [comment]
Hi @finnlewis - these are they: 

[Critical] Keyboard: Add a component with a media item (eg Image paragraph). Click Add Media. The keyboard focus does not move to the Add or select media modal.  ( https://www.drupal.org/project/layout_paragraphs/issues/3312143 )

Also, when you've selected a layout the modal refreshes and the focus moves back to the top of the modal so the next thing you focus on is the close button. 

Keyboard: when adding a new Page section we should be able to use the arrow keys to choose between the 3 layouts, however we are only able to move one option along. If we tab to the next field, and then tab back to the "choose a layout" field we can move one more space. 

(UX) Visual: The sections and layout boundaries are hidden unless you hover / focus on them. While this makes for a _clean_ UI I think it would be good to be able to see them all the time. (Or at least toggle them on or off)

Annoying: Edit, duplicate etc are links instead of buttons. Buttons do things, links go places.

**Comment by finnlewis** [comment]
OK - this works for localgov_subsites. 

I've tested locally and it works for existing demo content, enabling the localgov_demo module and then upgrading to layout_paragraphs 2.x works as expected. All content is still edible, but we have the new interface. 

Could I get some other eyes on it? @andybroomfield @stephen-cox @Adnan-cds @ekes @msayoung ?

Are we Ok to merge into the 2.x branch and to a point release? Feels safe to me, no breaking changes.

**Comment by finnlewis** [comment]
Actually - more work to do on this.

@stephen-cox and @ekes have thoughts....

move layout_paragraphs dependency to localgov_paragraphs and sync releases of major versions.

**Comment by finnlewis** [comment]
This has been superceded and done. :)

**Pull request closed without merging**
