### PR TITLE
Release preparation for 1.0.0-alpha4

### PR DESCRIPTION
**Pull request by Adnan-cds**
Bug fix for Call-out-box paragraphs causing WSOD.  This happens when such a Paragraph has no header text.

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]
Looks good to me!

**Review by finnlewis — CHANGES_REQUESTED** [review]
Hang on, actually, do we need to update the test config to make sure to test with PHP 7.4 ?

**Comment by Adnan-cds** [comment]
> do we need to update the test config to make sure to test with PHP 7.4 ?

Okay, I will add a change against the master branch.

**Comment by Adnan-cds** [comment]
> do we need to update the test config to make sure to test with PHP 7.4 ?

Done :)

**Review by finnlewis — APPROVED** [review]
Nice!

**Comment by Adnan-cds** [comment]
Thanks.  Merging ...

**Comment by Adnan-cds** [comment]
Release [1.0.0-alpha4](https://packagist.org/packages/localgovdrupal/localgov_subsites#1.0.0-alpha4) is out :)

**Pull request merged**
