### PR TITLE
Account for Call out box with no header

### LINKED ISSUE #9: WSOD from migrated Call-out-box paragraph
This happens when the *localgov_header_text* field of the Call-out-box paragraph is nonexistent.

### PR DESCRIPTION
**Pull request by Adnan-cds**
Call-out-box paragraphs may not have any header text.  This is specially true for migrated content.  This change uses an empty string when header text is absent.

Resolved #9

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Blocked by test failure ticket #3

**Comment by finnlewis** [comment]
Merged master back in and re-triggered tests.

**Comment by Adnan-cds** [comment]
Thanks Finn :)

**Review by finnlewis — APPROVED** [review]
Looks good to me @Adnan-cds

**Comment by Adnan-cds** [comment]
Thanks Finn.  I am merging...

**Pull request merged**
